version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build Docker Images
          command: |
            set -x
            docker-compose -f docker/compose/circle.yaml build
      - run:
          name: Save Docker image layer cache
          command: |
            set -x
            docker save -o ~/.cache/uea-circle.tar uea-circle
            docker save -o ~/.cache/uea-mysql.tar uea-mysql
            docker save -o ~/.cache/uea-liquibase.tar uea-liquibase

      - save_cache:
          key: uea-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/uea-circle.tar
            - ~/.cache/uea-mysql.tar
            - ~/.cache/uea-liquibase.tar

  test_1:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - uea-{{ .Branch }}
          paths:
            - ~/.cache/uea-circle.tar
            - ~/.cache/uea-mysql.tar
            - ~/.cache/uea-liquibase.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set -x
            docker load -i ~/.cache/uea-circle.tar
            docker load -i ~/.cache/uea-mysql.tar
            docker load -i ~/.cache/uea-liquibase.tar
      - run:
          name: Start containers
          command: |
            set -x
            docker-compose -f docker/compose/circle.yaml up -d
      - run:
          name: Wait container is ready
          command: |
            set -x
            sleep 20
      - run:
          name: NPM Install
          command: |
            set -x
            docker exec -it uea-api bash -c "git pull"
            docker exec -it uea-api bash -c "git checkout ${CIRCLE_BRANCH} && git pull"
            docker exec -it uea-api bash -c "npm install --unsafe-perm --only=dev"
      - run:
          name: Verify it's working
          command: |
            set -x
            docker exec -it uea-api bash -c " npm run test-unit"
      - run:
          name: Deploy to Codecov
          command: |
            set -x
            docker exec -it uea-api bash -c "nyc report --reporter=lcov"
            docker exec -it uea-api bash -c "codecov -t ${CODECOV_TOKEN}"

  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a5:94:99:bb:d9:3f:72:4c:52:f1:97:4c:0f:b0:28:b8"
      - run:
          name: Deployment
          command: |
            ssh -oStrictHostKeyChecking=no splab@ocarina.splab.ufcg.edu.br /home/splab/deploy/uea2.sh


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - test_1:
          requires:
            - build
      - deploy:
          requires:
            - test_1
          filters:
            branches:
              only: master
