## Enmetita kelkaj gravaj datumoj por unua funkciado de la sistemo
databaseChangeLog:
  - changeSet:
      id: 5
      author: Ana Ribeiro
      changes:
      ## Grupaj kategorioj##
        - insert:
            tableName: grupa_kategorio
            columns:
              - column:
                  name: id
                  value: 2
              - column:
                  name: nomo
                  value: Membreckategorio
        - insert:
            tableName: grupa_kategorio
            columns:
              - column:
                  name: id
                  value: 3
              - column:
                  name: nomo
                  value: Aldona membreckategorio
        - insert:
            tableName: grupa_kategorio
            columns:
              - column:
                  name: id
                  value: 4
              - column:
                  name: nomo
                  value: Junulara Grupo
        ## Administra rajto ##
        - insert:
            tableName: adminrajto
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: nomo
                  value: administranto
        - insert:
            tableName: adminrajto
            columns:
              - column:
                  name: id
                  value: 2
              - column:
                  name: nomo
                  value: juna administranto
        ## Baza retmembreco
        - insert:
            tableName: grupo
            columns:
              - column:
                  name: id
                  value: 1
              - column:
                  name: nomo
                  value: Baza retmembreco
  - changeSet:
      id: Aldoni urbon kiel varchar
      author: Ana Ribeiro
      changes:
      ## Grupaj kategorioj##
        - addColumn:
            columns:
              - column:
                  name: urbo
                  type: varchar(255)
            tableName: uzanto
        - addColumn:
            columns:
              - column:
                  name: urbo
                  type: varchar(255)
            tableName: aneco
  - changeSet:
      id: addUniqueConstraint
      author: Ana Ribeiro
      changes:
        - addUniqueConstraint:
            columnNames: landkodo
            tableName: lando
        - addUniqueConstraint:
            columnNames: mallongigilo
            tableName: grupo
