version: '3'
services:
  api:
    build: ../uea-docker/nodejs/
    image: uea-nodejs
    ports:
      - "3001:3000"
    volumes:
      - ../uea-api:/app
      - ../uea-mysql:/app/mysql
    environment:
      - DB_PASSWORD=u34p4ss-t3st3
      - DB_HOST=mysql-test
      - DB_PORT=3307
      - TEST=true
    links:
      - mysql:mysql-test
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=u34p4ss-t3st3
      - MYSQL_DATABASE=uea
    ports:
      - "3307:3306"
