version: '3'
services:
  api:
    build: ../dockerfiles/node-dev/
    image: uea-nodejs
    container_name: uea-api-test
    ports:
      - "3001:3001"
    environment:
      - LIQUIBASE=uea-liquibase-test
      - DB_PASSWORD=u34p4ss
      - DB_HOST=mysql-server
      - DB_PORT=3307
      - TEST=test
    volumes:
      - ../../:/app
    links:
      - mysql:mysql-server
    depends_on:
      - mysql

  liquibase:
    build: ../dockerfiles/liquibase
    image: uea-liquibase
    container_name: uea-liquibase-test
    environment:
      - DB_PASSWORD=u34p4ss
      - DB_HOST=mysql-server
      - DB_PORT=3307
      - MEDIO=MOCK
    links:
      - mysql:mysql-server
    depends_on:
      - mysql

  mysql:
    build: ../dockerfiles/mysql
    image: uea-mysql
    container_name: uea-datumbazo-test
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=u34p4ss
      - MYSQL_DATABASE=uea
    ports:
      - "3307:3306"
    volumes:
      - uea-testovolume:/var/lib/mysql

volumes:
  uea-testovolume:
